### ISSUE TITLE
Styling on Movie page

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/YiMovi#185]
- [x] Re-position text to be centred
- [x] re-position header text order
- [x] Prevent films taking up so much space (2 per line)
- [x] Prevent the change of font on "show more" drop down 
- [x] Allow users to see images more easily 
- [x] Add all sections to film navbar 
- [x] Move 'summary' section to bottom and rename 
- [x] Director name to be clickable
- [x] Font hierarchy
- [x] Prevent font changes in see more drop downs
