### ISSUE TITLE
Scope! 

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/YiMovi#205]
Key:
🐘  = time consuming issue
🔴  = needheroku/analytics access

## Keystone  ❗️❗️❗️❗️❗️
- [ ] Explore limitations of uploading photos 🐘 

## Vivienne
- [ ] Check all correct chinese translations are in place - i.e. headings 

## Done 🎉 
- [x] image jumping when clicking through buttons
- [x] add paragraphing to about section 
- [x] Chinese breadcrumbs 
- [x] Do not put up second clip for Zui Ai - Love for live
- [x] Add white space after "/" on genres etc
- [x] additional video links missing from database
- [x] Add correct contact email 

- [x] Reduce vertical padding / font size / make scrollable the movie list
![image](https://user-images.githubusercontent.com/26116988/35970205-6b407874-0cc1-11e8-890c-10c0f660ba3c.png)
- [x] too many options in navbar
- [x] Director name to underline on hover so show clickability on movie page
- [x] Google form to be connected to yimovi.site@gmail.com - also update link in website
- [x] PDF in movie navbar
- [x] Display PDFs in section called references - @jen-harris
- [x] Reduce horizontal padding on mobile about section
![image](https://user-images.githubusercontent.com/26116988/35970217-76e2808c-0cc1-11e8-8660-05da08623edd.png)
- [x] Host the website: upgrading to a paid plan and switch to a custom domain name 1 day 🔴 
- [x] Homosexual/lesbian film needs to be separated with white space 
- [x] Chinese site should have Chinese main header on Movies etc - may need to contact Vivienne?
- [x] Prevent the change of font on "show more" drop down - Mama points for discussion
- [x] Remame 'summary' to 'intro' on film navbar - @jen-harris
- [x] Allow summary to be seen for specific themes/genres (currently happens with Ageing and directors - possibly is in place already?) - @maxgerber 
- [x] Tag whether films are full length or clips 
- [x] All gray font to be white - @jen-harris
- [x] remove doubling of chinese on films - @jen-harris
- [x] Create a google analytics tutorial 🔴 
- [x] Explore and scope what is needed in order to host PDF’s on the website for future implementation - may not be possible with KeyStone need to update Vivienne 🐘  😢 
- [x] Screening notes sub heading - @jen-harris
- [x] underline for navbar not bold @jen-harris
- [x] padding on home page - @jen-harris
- [x] doubling of titles. Needs deleting from keystone
- [x] Navbar on hover go bold - @jen-harris
- [x] Footer to bottom of page - @jen-harris
- [x] Allow users to see images more easily 🐘 
- [x] Input new team links in about section & pictures 🔴 
- [x] Correct capitalisation of headings
- [x] Contact us page headings 
- [x] fix proportions of images & films - @jen-harris
- [x] Share button in navbar - @jen-harris
- [x] New design for about section
- [x] Images/films stretching on movie profiles
- [x] Pinyin to be in italics 🔴 
- [x] Font hierarchy
- [x] Link to change site should be used from any page and change "CHN" to chinese symbols
- [x] have social icons under 'share' heading 
- [x] navbar needs to have chinese version
- [x] Spend time understanding codebase
- [x] Implement translate button English/chinese 
- [x] Sort all subsections alphabetically
- [x] Bug fixing 
- [x] User testing session and review 
- [x] Scoping UI & UX (design) changes needed according to user testing session. We will then decide what can be done in the current sprint and what will be put on the backlog for future work 
- [x] Implementing design changes by designer and devs 
- [x] Resolve issue with sending of the form :bug: 
- [x] Prevent autoplay on films :bug: 
- [x] Navbar :star: 
- [x] Colour scheme & Slight re-design
- [x] FIlm Page
    - [x] Re-position text
    - [x] Add all sections to film navbar 
    - [x] Move 'summary' section to bottom and rename 
    - [x] Director name to be clickable - needs a helper function to make lower case and replace white space with '-' @jen-harris
 - [x] Move about us section to higher on the page
 - [x] adjust order of film navbar
 - [x] Summary section should move to bottom of page
 - [x] mobie friendly navbar & ensure translation to chinese 🐘  😱  @maxgerber 
 - [x] Google form 
- [x] Link to google form from home page
 - [x] Review capitalisation 
- [x] Move contact us section to bottom of home page
 - [x] Have more text visible before it says 'show more'
  - [x] Only display 'show more' button when the text is over limit
 - [x] Fixed titles to be correct
